title: GitHub Page
author: gtdalton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a pagae used to learn how to use GitHub Pages with markdown

# social links
twitter_username: gtommyd1
github_username:  gtdalton

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
